apiVersion: v1
kind: Service
metadata:
  name: {{ include "spring.fullname" . }}
  labels:
    app: {{ include "spring.fullname" . }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.app.server.port }}
      targetPort: {{ .Values.app.server.port }}
      nodePort: {{ .Values.ports.nodePort }}
  selector:
    app: {{ include "spring.fullname" . }}