apiVersion: v2
name: kafka
version: 1.0.0
appVersion: 1.0.0
type: application
description: A Helm chart for Kubernetes to deploy springboot application, zookeeper and kafka instances.
dependencies:
  - name: cp-kafka
    version: 1.1.0
    repository: file://./charts/cp-kafka
    condition: cp-kafka.enabled
  - name: cp-zookeeper
    version: 1.1.0
    repository: file://./charts/cp-zookeeper
    condition: cp-zookeeper.enabled
  - name: cp-schema-registry
    version: 1.1.0
    repository: file://./charts/cp-schema-registry
    condition: cp-schema-registry.enabled