nameOverride: kafka-app
fullnameOverride: kafka-application

cp-kafka:
  brokers: 1
  configurationOverrides:
    "offsets.topic.replication.factor": "1"
    "metric.reporters":

cp-zookeeper:
  servers: 1