apiVersion: v1
kind: Service
metadata:
  name: {{ template "cp-schema-registry.fullname" . }}
  labels:
    app: {{ template "cp-schema-registry.name" . }}
    chart: {{ template "cp-schema-registry.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - name: http-sr
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.servicePort }}
      nodePort: {{ .Values.nodeport }}
  selector:
    app: {{ template "cp-schema-registry.name" . }}
    release: {{ .Release.Name }}
