apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
        - name: spring
          image: shirmanton/spring:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080