apiVersion: v1
kind: Service
metadata:
  name: spring
  namespace: default
spec:
  selector:
    app: spring
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort