replicaCount: 1
image:
  repository: shirmanton/spring
  tag: latest
  pullPolicy: Always
nameOverride: spring-app
fullnameOverride: spring-application
ports:
  nodePort: 32090
app:
  server:
    port: 8080
  kafka:
    brokerHost: kafka-cp-kafka-headless
    brokerPort: 9092
    topic:
      name: app-topic
      partitions: 1
      replicas: 1
      customerKey: customer-key
    schemaHost: kafka-cp-schema-registry
    schemaPort: 8081
    autoRegisterSchemas: true